### Get all cats
GET http://127.0.0.1:3000/api/v1/cats

### GET all users
GET http://127.0.0.1:3000/api/v1/users

### Get single cat
GET http://127.0.0.1:3000/api/v1/cats/47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwibmFtZSI6IlBhdHJpa0FkbWluIiwidXNlcm5hbWUiOiJ5YWhoYXN6IiwiZW1haWwiOiJwYXRyaWtAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTkyNDEyLCJleHAiOjE3MTMwNzg4MTJ9.b2su_H5S9fuc7s4QOTgaZKLlyLI7wgEgeXfmL7dlysY


### Get single user
GET http://127.0.0.1:3000/api/v1/users/37

### Get cat by user id
GET http://127.0.0.1:3000/api/v1/users/37/cats

### Test is owner
PUT http://127.0.0.1:3000/api/v1/cats/47
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwibmFtZSI6IlBhdHJpa0FkbWluIiwidXNlcm5hbWUiOiJ5YWhoYXN6IiwiZW1haWwiOiJwYXRyaWtAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTkyNDEyLCJleHAiOjE3MTMwNzg4MTJ9.b2su_H5S9fuc7s4QOTgaZKLlyLI7wgEgeXfmL7dlysY
Content-Type: application/json

{
  "cat_name": "Petteri",
  "weight": 5,
  "birthdate": "2021-06-04"
}

### Add a new cat
POST http://127.0.0.1:3000/api/v1/cats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwibmFtZSI6IlBhdHJpa0FkbWluIiwidXNlcm5hbWUiOiJ5YWhoYXN6IiwiZW1haWwiOiJwYXRyaWtAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTkyNDEyLCJleHAiOjE3MTMwNzg4MTJ9.b2su_H5S9fuc7s4QOTgaZKLlyLI7wgEgeXfmL7dlysY
Content-Type: application/json

{
  "cat_name": "PatrikKissa",
  "weight": 3.2,
  "owner": 41,
  "filename": "patrikkissa.jpg",
  "birthdate": "21-06-04"
}

### Add a new user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name" : "PatrikAdmin",
  "username" : "yahhasz",
  "email" : "patrik@gmail.com",
  "password" : "admin123",
  "role" : "admin"
}

### test
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "username": "yahhasz",
  "password": "admin123"
}

### Test login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "yahhasz",
  "password": "admin123"
}


// token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MCwibmFtZSI6IlBhdHJpayIsInVzZXJuYW1lIjoieWFoaGFzIiwiZW1haWwiOiJ1cnBvQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzEyOTI1MjU3LCJleHAiOjE3MTMwMTE2NTd9.Nn3bH-ojckgretlwOVFXgUYVUtBmnkAl3YaUdKY6OSM

### Upload vito cat image to backend
POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="cat_name"

Vito
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="owner"

37
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="vito.png"
Content-Type: image/png

< ./images/vito.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Upload veikko cat image to backend
POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New cat title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="veikko.png"
Content-Type: image/png

< ./images/veikko.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Upload vito gif cat image to backend
# should save file as .jpg
POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New cat title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="vito.png"
Content-Type: image/gif

< ./images/vito.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
